### PR TITLE
Android module

### PR DESCRIPTION
**Pull request by orenk86**

### CODE REVIEW

**Comment by medeeiros** [comment]
hey! I see some good changes here. You don't want to merge it?

**Comment by orenk86** [comment]
Hi @GuilhermeMedeiros ,
I made this pull request to your repo by mistake, I was going to do it to a different fork. That's why I closed it immediately.
The changes include, among other things, integration of another library for Android (not VideoCore).
Do you want this anyway? I can remove the Android stuff and create a new PR if you want...

**Comment by medeeiros** [comment]
yes, I'd very much like to have the ios improvements. Thanks!

**Comment by orenk86** [comment]
Sure thing. I'll try to do it later today or tomorrow.

**Pull request closed without merging**
